name: build-and-deploy
run-name: ${{ github.actor }} is building and deploying ${{ github.event.repository.name }}

env:
  DOCKER_IMAGE: simhub-server
  DOCKER_CONTAINER: simhub-server

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted
    environment: development

    steps:
      - uses: actions/checkout@v3
      - run: >
          docker build -t ${{ env.DOCKER_IMAGE }}:development .

  deploy:
    runs-on: self-hosted
    environment: development
    needs: build

    name: deploy
    steps:
      - uses: actions/checkout@v3
      - run: docker container rm -f ${{ env.DOCKER_CONTAINER }} || true
      - run: |
          docker run -d -p 8000:8000 --name ${{ env.DOCKER_CONTAINER }} \
          -e PORT=${{ env.PORT }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e DATABASE_URL=${{ env.DATABASE_URL }} \
          ${{ env.DOCKER_IMAGE }}:development
