name: build-and-deploy
run-name: ${{ github.actor }} is building and deploying ${{ github.event.repository.name }}

env:
  DOCKER_IMAGE: simhub-server
  DOCKER_CONTAINER: simhub-server

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted

    name: build
    steps:
      - uses: actions/checkout@v3
      # - run: >
      #     docker build -t ${{ env.DOCKER_IMAGE }}:development .

  deploy:
    runs-on: self-hosted
    needs: build

    name: deploy
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - run: docker container rm -f ${{ env.DOCKER_CONTAINER }} || true
      - run: echo ${{ env.JWT_SECRET }}
